version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
